### ISSUE TITLE
put color on elements, for player with majority

### ISSUE THREAD

**Issue by vatirim** [Koala00/BLStudio-TowerGame#10]

**Comment by vatirim** [comment]
do this in GridPositionElements.endTurn() and call this in Grid.endTurn() after GridTowers.endTurn().

**Comment by Koala00** [comment]
colorier le contenu plutôt que les bords
une couleur plus claire?
Color.Lerp, pour faire un dégradé entre deux couleurs (prendre blanc et ...)
