### ISSUE TITLE
Calcul de fin partie

### ISSUE THREAD

**Issue by Koala00** [Koala00/BLStudio-TowerGame#5]
1. nombre de tours limité
2. 80% plateau contrôlé => fin de partie (100% plateau rempli?)
3. nombre de forteresses atteint

compter les cases par pourcentage, quel joueur est majoritaire?

**Comment by Koala00** [comment]
1. nombre de tours limité
2. 80% plateau contrôlé => fin de partie (100% plateau rempli?)
3. nombre de forteresses atteint

**Comment by vatirim** [comment]
Pour option 2. on a besoin du score du joueur, relié aux nombre des cases contrôlées.

**Comment by vatirim** [comment]
Finished 1. and 2.
